#!/usr/bin/env sh
/Users/jtanner/projects/random_collage/random_collage -i '~/Pictures/family backgrounds' -b photo
/Users/jtanner/projects/random_collage/random_collage -i '~/Pictures/treasure map' -s
/Users/jtanner/projects/random_collage/random_collage -i '~/Pictures/family backgrounds' -b photo -l border -r 0.20 -a 16
/Users/jtanner/projects/random_collage/random_collage -i '~/Pictures/family backgrounds' -l mosaic -n 12