#!/usr/bin/env ruby
require 'rubygems'
require 'trollop'
require File.dirname(__FILE__) + '/init'

opts = Trollop::options do
  opt :input_dir,        "Directory of images to use for the collage", :default => '~/Pictures/'
  opt :output_dir,       "Where to store the resulting image", :default => '~/Pictures/collages'
  opt :width,            "Width of resulting image",  :default => 1280
  opt :height,           "Height of resulting image", :default => 800
  opt :layout,           "collage, border, or mosaic", :default => 'collage'
  opt :using_iphoto,     "If --input-dir is an iPhoto Library then use this flag", :default => false
  opt :image_ratio,      "Size ratio of the collaged images compared to the width and height (a range will also work i.e. 0.3..0.4)", :default => '0.35', :short => 'r'
  opt :number_of_photos, "Number of photos to use from --input-dir (a range will also work i.e. 20..30)", :default => '25'
  opt :angle,            "Max degree of angle, it's random from minus angle to angle (i.e. -20 to 20)", :default => 20
  opt :background,       "Give a color name or 'photo' to use one of the photos.", :default => 'black'
  opt :show_titles,      "Show titles on the polaroid border (uses a titleized version of the file name)", :default => false
  opt :collages_to_keep, "Number of images to keep in the --output-dir (use 'all' to keep all files)", :default => 20
end
opts.delete(:help)


float_range_options = [:image_ratio]
float_range_options.each do |option|
  opts[option] = Range.new(*opts[option].split('..').map { |i| i.to_f }) if opts[option] =~ /^0\.\d+..0\.\d+$/
  if opts[option].is_a?(String)
    Trollop::die option, "must be either a float or a range of floats (i.e. 0.3..0.4) between 1 and 0" unless opts[option] =~ /^0\.\d+$/
    opts[option] = opts[option].to_f
  end
end

integer_range_options = [:number_of_photos]
integer_range_options.each do |option|
  opts[option] = Range.new(*opts[option].split('..').map { |i| i.to_i }) if opts[option] =~ /^\d+..\d+$/
  if opts[option].is_a?(String)
    Trollop::die option, "must be either an integer or a range of integers (i.e. 20..30)" unless opts[option] =~ /^\d+$/
    opts[option] = opts[option].to_i
  end
end

rm = RandomCollage.new(opts)
rm.write!
